### ISSUE TITLE
JSON resources in 1.0.2 don't work

### ISSUE THREAD

**Issue by vadi2** [brianpos/FhirPathTester#1]
Complains with:

> STU3 Resource read error:
Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

As a workaround, can use https://fhir-formats.github.io/ to convert json to xml

**Comment by brianpos** [comment]
This still an issue? I thought it was binding to a newer version than that.

**Comment by vadi2** [comment]
I tried out the latest release but it just crashes when I press extract or validate :(

**Comment by brianpos** [comment]
Can you try this with the 1.0.4 version?

**Comment by vadi2** [comment]
Yep, works! Thank you.
